# Generated by Django 5.0.3 on 2024-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
