# Generated by Django 5.0.3 on 2024-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
